var $jscomp={scope:{},findInternal:function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6-impl","es3");(function(){});$(document).ready(function(){$(".auto-height-text-area").each(function(){}).on("input",function(){$(this).css({height:"auto","overflow-y":"hidden"}).height(this.scrollHeight)})});var BannerWithSearch=function(a){this.$root=a;this.id=this.$root.data("id");this.search_event_=this.search_bar=this.$search_bar=null;this.init();this.initWidgetEvents();this.initEvents()};BannerWithSearch.prototype.EVENT={BANNER_WITH_SEARCH_SEARCH:"banner-with-search-search"};BannerWithSearch.prototype.init=function(){this.$search_bar=this.$root.find("#"+this.id+"-search-bar");this.search_bar=new SearchBar(this.$search_bar)};
BannerWithSearch.prototype.initEvents=function(){this.$search_bar.on(SearchBar.prototype.EVENT.SEARCH_BAR_SEARCH,function(a,b){this.triggerSearch(b)}.bind(this))};BannerWithSearch.prototype.initWidgetEvents=function(){this.search_event_=new CustomEvent(this.EVENT.BANNER_WITH_SEARCH_SEARCH)};BannerWithSearch.prototype.triggerSearch=function(a){this.$root.trigger(this.EVENT.BANNER_WITH_SEARCH_SEARCH,[a])};var BidContainer=function(a){this.$root=a;this.$bid_list={};this.init()};BidContainer.prototype.init=function(){var a=this;$.each($(".bid"),function(b,c){var d=$(c).find("id");a.$bid_list[d]=new Bid($(c))})};var BidReplyContainer=function(a){this.$root=a;this.id=a.data("id");this.bid_id=a.data("bid_id");this.offset=a.data("offset");this.first_created_at=a.data("first_created_at");this.item_area=this.item_transition_class=null;this.bid_reply_template_id="bid-reply-template-id";this.load_more_replies_class="bid-reply-container-load-replies";this.total_replies_class="bid-reply-container-total-replies";this.init();this.initEvents()};
BidReplyContainer.prototype.init=function(){this.item_transition_class="bid-reply-container-item-transition";this.item_area="bid-reply-container-item-area"};BidReplyContainer.prototype.initEvents=function(){$(document).on("click","#"+this.id,function(a){a.target&&$(a.target).hasClass(this.load_more_replies_class)&&this.getMoreReplies()}.bind(this))};
BidReplyContainer.prototype.getMoreReplies=function(){$.ajax({url:$("#base-url").val()+"/bid/get-more-replies",type:"post",context:this,data:{bid_id:this.bid_id,first_created_at:this.first_created_at,offset:this.offset},success:function(a){a=JSON.parse(a);1===a.status&&(this.appendToItemArea(a.view),this.substractTotalMoreReplies(a.count),this.offset+=parseInt(a.count),this.last_created_at=a.last_created_at)}})};
BidReplyContainer.prototype.setNewMessage=function(a){var b="bid-reply-transition-"+(new Date).getUTCMilliseconds();this.addToTransition(a,b);$.ajax({url:$("#base-url").val()+"/bid/reply",type:"post",context:this,data:{bid_id:this.bid_id,message:a},success:function(a){a=JSON.parse(a);1===a.status&&this.prependToItemArea(a.view);this.removeTransition(b)}})};
BidReplyContainer.prototype.addToTransition=function(a,b){var c=CommonLibrary.getBidReplyTemplate().replace(this.bid_reply_template_id,b),c=c.replace("{message}",a);$("#"+this.id).find("."+this.item_transition_class).prepend(c)};BidReplyContainer.prototype.removeTransition=function(a){$("#"+this.id).find("#"+a).remove()};BidReplyContainer.prototype.prependToItemArea=function(a){$("#"+this.id).find("."+this.item_area).prepend(a)};
BidReplyContainer.prototype.appendToItemArea=function(a){$("#"+this.id).find("."+this.item_area).append(a)};BidReplyContainer.prototype.substractTotalMoreReplies=function(a){var b=$("#"+this.id).find("."+this.total_replies_class),c=parseInt(b.html());0>=c-a?b.parent().addClass("hide"):b.html(c-a)};var Bid=function(a){this.$root=a;this.id=a.data("id");this.bid_id=a.data("bid_id");this.$bid_reply_container=this.bid_reply_container=this.bid_reply_container_id=this.bid_reply_area_class=this.text_area_id=null;this.bid_give_class="bid-give";this.cancel_give_class="bid-cancel-give";this.bid_delete_class=null;this.init();this.initEvents()};
Bid.prototype.init=function(){this.text_area_id=this.id+"-reply-box";this.bid_reply_area_class="bid-reply-area";this.bid_reply_container_id=this.id+"-bid-reply-container";this.bid_delete_class="bid-delete";this.$bid_reply_container=$("#"+this.id).find("#"+this.bid_reply_container_id);this.bid_reply_container=new BidReplyContainer(this.$bid_reply_container)};
Bid.prototype.initEvents=function(){var a={13:!1};$(document).on("click","#"+this.id,function(a){a.target&&$(a.target).hasClass(this.bid_give_class)?($("#"+this.id).find("."+this.cancel_give_class).removeClass("hide"),$("#"+this.id).find("."+this.bid_give_class).addClass("hide"),$.ajax({url:$("#base-url").val()+"/bid/give",type:"post",context:this,data:{bid_id:this.bid_id},success:function(a){},error:function(a){}})):a.target&&$(a.target).hasClass(this.cancel_give_class)?($("#"+this.id).find("."+
this.bid_give_class).removeClass("hide"),$("#"+this.id).find("."+this.cancel_give_class).addClass("hide"),$.ajax({url:$("#base-url").val()+"/bid/cancel-give",type:"post",context:this,data:{bid_id:this.bid_id},success:function(a){},error:function(a){}})):a.target&&$(a.target).hasClass(this.bid_delete_class)&&ConfirmationModal.show("Are you sure to remove your proposal?",function(a){a&&this.deleteBid()}.bind(this))}.bind(this));$(document).on("keypress","#"+this.id,function(b){b.target&&$(b.target).prop("id")===
this.text_area_id&&b.keyCode in a&&(a[b.keyCode]=!0,a[13]&&!b.shiftKey&&""!==this.getReplyText().trim()&&(this.submitReply(),b.preventDefault()))}.bind(this));$(document).on("keyup","#"+this.id,function(b){b.target&&$(b.target).prop("id")===this.text_area_id&&b.keyCode in a&&(a[b.keyCode]=!1)}.bind(this))};Bid.prototype.getReplyHtml=function(){return $("#"+this.id).find("#"+this.text_area_id).html()};Bid.prototype.getReplyText=function(){return $("#"+this.id).find("#"+this.text_area_id).text()};
Bid.prototype.submitReply=function(){this.bid_reply_container.setNewMessage(this.getReplyHtml());this.emptyReplyBox()};Bid.prototype.emptyReplyBox=function(){$("#"+this.id).find("#"+this.text_area_id).html("")};Bid.prototype.deleteBid=function(){$("#"+this.id).remove();$.ajax({url:$("#base-url").val()+"/bid/delete",data:{bid_id:this.bid_id},type:"post",success:function(a){}})};var BidderList=function(a){this.$root=a;this.$cancel_button=this.$give_button=null;this.stuff_id=a.data("stuff_id");this.init();this.initEvents()};BidderList.prototype.init=function(){this.$give_button=this.$root.find(".bidder-list-item-give-button");this.$cancel_button=this.$root.find(".bidder-list-item-cancel-button")};
BidderList.prototype.initEvents=function(){var a=this;this.$give_button.click(function(b){b=$(this).data("user_id");$(this).addClass("bidder-list-hide");$(this).parent().find(".bidder-list-item-cancel-button").removeClass("bidder-list-hide");$.ajax({url:$("#base-url").val()+"/post/give",type:"post",context:this,data:{user_id:b,stuff_id:a.stuff_id},success:function(a){0===JSON.parse(a).status&&($(this).removeClass("bidder-list-hide"),$(this).parent().find(".bidder-list-item-cancel-button").addClass("bidder-list-hide"))}})});
this.$cancel_button.click(function(b){b=$(this).data("user_id");$(this).addClass("bidder-list-hide");$(this).parent().find(".bidder-list-item-give-button").removeClass("bidder-list-hide");$.ajax({url:$("#base-url").val()+"/post/cancel-give",type:"post",context:this,data:{user_id:b,stuff_id:a.stuff_id},success:function(a){0===JSON.parse(a).status&&($(this).removeClass("bidder-list-hide"),$(this).parent().find(".bidder-list-item-cancel-button").addClass("bidder-list-hide"))}})})};$(function(){$(document).on("mouseover",".button-with-tooltip-button",function(a){a=$(this).data("widget");$("#"+a).find(".button-with-tooltip-tooltip").removeClass("button-with-tooltip-hide")});$(document).on("mouseout",".button-with-tooltip-button",function(a){a=$(this).data("widget");$("#"+a).find(".button-with-tooltip-tooltip").addClass("button-with-tooltip-hide")})});var ChangeImage=function(a){this.$root=a;this.cancel_event_=this.image_changed_event_=this.$cancel_button=this.$ok_button=this.currentFile=this.imageValid=this.$select_photo_input=this.$image=this.$image_error=null;this.init();this.initEvents();this.initWidgetEvents()};
ChangeImage.prototype.init=function(){this.$select_photo_input=this.$root.find(".change-image-select-photo");this.$image_error=this.$root.find(".change-image-error");this.$image=this.$root.find(".change-image-view");this.$ok_button=this.$root.find(".change-image-button-ok");this.$cancel_button=this.$root.find(".change-image-button-cancel")};
ChangeImage.prototype.initWidgetEvents=function(){this.image_changed_event_=new CustomEvent(ChangeImage.prototype.EVENT.CHANGE_IMAGE_IMAGE_CHANGED);this.cancel_event_=new CustomEvent(ChangeImage.prototype.EVENT.CHANGE_IMAGE_CANCEL)};
ChangeImage.prototype.initEvents=function(){var a=this;this.$cancel_button.click(function(a){this.triggerCancelEvent_()}.bind(this));this.$ok_button.click(function(a){$.ajax({url:$("#base-url").val()+"/site/upload-image",type:"post",data:this.currentFile,context:this,processData:!1,enctype:"multipart/form-data",cache:!1,contentType:!1,success:function(a){a=JSON.parse(a);1===a.status&&this.triggerImageChangedEvent_({image_id:a.image_id,image_path:a.image_path})}})}.bind(this));this.$select_photo_input.change(function(b){if(this.files&&
this.files[0]){b=new FileReader;if(25<this.files[0].size/1024/1024)return a.showError(a.$image_error,"File size cannot be larger than 20 MB"),a.imageValid=!1;a.imageValid=!0;a.hideError(a.$image_error);a.currentFile=new FormData;a.currentFile.append("image",this.files[0]);b.onload=function(b){a.$image.attr("src",b.target.result);a.$ok_button.removeClass("hide")};b.readAsDataURL(this.files[0])}})};ChangeImage.prototype.showError=function(a,b){a.html(b)};ChangeImage.prototype.hideError=function(a){a.html()};
ChangeImage.prototype.EVENT={CHANGE_IMAGE_IMAGE_CHANGED:"change-image-image-changed",CHANGE_IMAGE_CANCEL:"change-image-cancel"};ChangeImage.prototype.triggerImageChangedEvent_=function(a){this.$root.trigger(this.EVENT.CHANGE_IMAGE_IMAGE_CHANGED,[a])};ChangeImage.prototype.triggerCancelEvent_=function(){this.$root.trigger(this.EVENT.CHANGE_IMAGE_CANCEL)};var CommonLibrary=function(){};CommonLibrary.isGuest=function(a){void 0===a&&(a=!0);($guest=null===$("#current-user-id").val()||""===$("#current-user-id").val())&&a&&$("#login-modal").modal("show").load($(this).attr("value"));return $guest};CommonLibrary.validateEmail=function(a){return/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(a)};CommonLibrary.getBidReplyTemplate=function(){return $("#bid-reply-template").html()};
CommonLibrary.showError=function(a,b){a.html(b)};CommonLibrary.hideError=function(a){a.html("")};CommonLibrary.showCommonLoading=function(){$("#common-loading").show()};CommonLibrary.hideCommonLoading=function(){$("#common-loading").hide()};var ConfirmationModal=function(a){this.id=a.data("id");this.$root=a;this.cancel_event=this.ok_event=this.text_class=this.cancel_class=this.ok_class=null;this.init();this.initEvents();this.initWidgetEvents()};ConfirmationModal.prototype.EVENTS={CONFIRMATION_MODAL_OK:"confirmation-modal-ok",CONFIRMATION_MODAL_CANCEL:"confirmation-modal-cancel"};ConfirmationModal.prototype.init=function(){this.ok_class="confirmation-modal-ok";this.cancel_class="confirmation-modal-cancel";this.text_class="modal-body"};
ConfirmationModal.prototype.initEvents=function(){$(document).on("click","#"+this.id,function(a){a.target&&$(a.target).hasClass(this.ok_class)?this.triggerOkEvent():a.target&&$(a.target).hasClass(this.cancel_class)&&this.triggerCancelEvent()}.bind(this))};ConfirmationModal.prototype.initWidgetEvents=function(){this.ok_event=new CustomEvent(this.EVENTS.CONFIRMATION_MODAL_OK);this.cancel_event=new CustomEvent(this.EVENTS.CONFIRMATION_MODAL_CANCEL)};
ConfirmationModal.show=function(a,b){var c=$("#confirmation-modal"),d=new ConfirmationModal(c);d.setText(a);d.show();c.on(ConfirmationModal.prototype.EVENTS.CONFIRMATION_MODAL_OK,function(a){b(!0);d.hideAndDelete()}.bind(this));c.on(ConfirmationModal.prototype.EVENTS.CONFIRMATION_MODAL_CANCEL,function(a){d.hideAndDelete()}.bind(this))};ConfirmationModal.prototype.setText=function(a){$("#"+this.id).find("."+this.text_class).html(a)};
ConfirmationModal.prototype.hideAndDelete=function(){$("#"+this.id).modal("hide");$(document).off("click","#"+this.id)};ConfirmationModal.prototype.hide=function(){$("#"+this.id).modal("hide")};ConfirmationModal.prototype.show=function(){$("#"+this.id).modal("show")};ConfirmationModal.prototype.triggerOkEvent=function(){$("#"+this.id).trigger(this.EVENTS.CONFIRMATION_MODAL_OK)};ConfirmationModal.prototype.triggerCancelEvent=function(){$("#"+this.id).trigger(this.EVENTS.CONFIRMATION_MODAL_CANCEL)};var CreatePost=function(a){this.$root=a;this.id=a.data("id");this.imageValid=!0;this.loading=this.$loading=this.$upload_photo_modal=this.$select_photo_input=this.$create_button=this.$description_error=this.$title_error=this.$tags_error=this.$quantity=this.$image=this.$description=this.$title=this.$tags=null;this.init();this.initEvents()};
CreatePost.prototype.init=function(){this.$tags=this.$root.find("#create-post-information-tags");this.$title=this.$root.find(".create-post-information-title");this.$description=this.$root.find(".create-post-information-description");this.$image=this.$root.find(".create-post-image-view");this.$quantity=this.$root.find(".create-post-information-quantity");this.$tags_error=this.$root.find(".create-post-information-tags-error");this.$title_error=this.$root.find(".create-post-information-title-error");
this.$description_error=this.$root.find(".create-post-information-description-error");this.$image_error=this.$root.find(".create-post-information-image-error");this.$quantity_error=this.$root.find(".create-post-information-quantity-error");this.$create_button=this.$root.find(".create-post-create");this.$select_photo_input=this.$root.find(".create-post-image-select-photo");this.$upload_photo_modal=this.$root.find("#"+this.id+"-modal");this.$loading=this.$root.find("#"+this.id+"-loading");this.loading=
new Loading(this.$loading);this.currentFile=null};
CreatePost.prototype.initEvents=function(){var a=this;this.$select_photo_input.change(function(b){if(this.files&&this.files[0]){b=new FileReader;if(25<this.files[0].size/1024/1024)return a.showError(a.$image_error,"File size cannot be larger than 20 MB"),a.imageValid=!1;a.imageValid=!0;a.hideError(a.$image_error);a.currentFile=new FormData;a.currentFile.append("image",this.files[0]);b.onload=function(b){a.$image.attr("src",b.target.result)};b.readAsDataURL(this.files[0])}});this.$create_button.click(function(a){this.validateInClient()&&
this.uploadImage()}.bind(this))};CreatePost.prototype.uploadImage=function(){this.loading.setMessage("Uploading Image");this.loading.show();$.ajax({url:$("#base-url").val()+"/site/upload-image",type:"post",data:this.currentFile,context:this,processData:!1,enctype:"multipart/form-data",cache:!1,contentType:!1,success:function(a){a=JSON.parse(a);1===a.status&&this.postData(a.image_id)}})};
CreatePost.prototype.postData=function(a){this.loading.setMessage("Creating Post");this.loading.show();CommonLibrary.showCommonLoading();$.ajax({url:$("#base-url").val()+"/post/process-create",type:"post",context:this,data:{title:this.getTitleVal(),description:this.getDescriptionVal(),image_id:a,tags:this.getTagsVal(),quantity:this.getQuantityVal()},success:function(a){a=JSON.parse(a);1===a.status&&(window.location.href=$("#base-url").val()+"/post/"+a.stuff_id+"/"+this.getTitleVal());CommonLibrary.hideCommonLoading()}})};
CreatePost.prototype.validateInClient=function(){var a=!0;this.imageValid?null===this.getImageVal()||""===this.getImageVal()?(a=!1,this.showError(this.$image_error,"Please put some image")):this.hideError(this.$image_error):a=!1;null===this.getTitleVal()||""===this.getTitleVal()?(a=!1,this.showError(this.$title_error,"Title cannot be empty")):this.hideError(this.$title_error);null===this.getDescriptionVal()||""===this.getDescriptionVal()?(a=!1,this.showError(this.$description_error,"Please put some descriptions about the stuff")):
this.hideError(this.$description_error);null===this.getTagsVal()||0===this.getTagsVal().length?(a=!1,this.showError(this.$tags_error,"Please choose at least 1 tag")):this.hideError(this.$tags_error);0===this.getQuantityVal()||null===this.getQuantityVal()?(a=!1,this.showError(this.$quantity_error,"Quantity should be at least 1")):this.hideError(this.$quantity_error);return a};CreatePost.prototype.showError=function(a,b){a.html(b)};CreatePost.prototype.hideError=function(a){a.html("")};
CreatePost.prototype.getTitleVal=function(){return this.$title.val()};CreatePost.prototype.getDescriptionVal=function(){return this.$description.html()};CreatePost.prototype.getTagsVal=function(){return this.$tags.val()};CreatePost.prototype.getImageVal=function(){return this.$select_photo_input.val()};CreatePost.prototype.getQuantityVal=function(){var a=this.$quantity.val();null===a&&(a=0);return parseInt(a)};var EditPost=function(a){this.$root=a;this.id=a.data("id");this.stuff_id=a.data("stuff_id");this.cancel_event_=this.$edit=this.$cancel=this.$tags_error=this.$quantity_error=this.$description_error=this.$title_error=this.$quantity=this.$description=this.$title=this.$tags=null;this.init();this.initEvents();this.initWidgetEvents()};
EditPost.prototype.init=function(){this.$quantity_error=this.$root.find(".edit-post-quantity-error");this.$description_error=this.$root.find(".edit-post-description-error");this.$tags_error=this.$root.find(".edit-post-tags-error");this.$title_error=this.$root.find(".edit-post-title-error");this.$quantity=this.$root.find(".edit-post-quantity");this.$description=this.$root.find(".edit-post-description");this.$tags=this.$root.find("#"+this.id+"-tags");this.$title=this.$root.find(".edit-post-title");
this.$edit=this.$root.find(".edit-post-edit");this.$cancel=this.$root.find(".edit-post-cancel")};EditPost.prototype.initEvents=function(){this.$cancel.click(function(a){this.triggerCancelEvent()}.bind(this));this.$edit.click(function(a){$valid=this.validateClient();this.sendEdit()}.bind(this))};
EditPost.prototype.sendEdit=function(){this.disableButton();$.ajax({url:$("#base-url").val()+"/post/edit",type:"post",context:this,data:{title:this.getTitleVal(),description:this.getDescriptionVal(),tags:this.getTagsVal(),quantity:this.getQuantityVal(),stuff_id:this.stuff_id},success:function(a){1===JSON.parse(a).status?window.location.reload():this.enableButton()}})};
EditPost.prototype.validateClient=function(){var a=!0;null===this.getTitleVal()||""===this.getTitleVal()?(a=!1,CommonLibrary.showError(this.$title_error,"Title cannot be empty")):CommonLibrary.hideError(this.$title_error);null===this.getDescriptionVal()||""===this.getDescriptionVal()?(a=!1,CommonLibrary.showError(this.$description_error,"Please put some descriptions about the stuff")):CommonLibrary.hideError(this.$description_error);null===this.getTagsVal()||0===this.getTagsVal().length?(a=!1,CommonLibrary.showError(this.$tags_error,
"Please choose at least 1 tag")):CommonLibrary.hideError(this.$tags_error);0===this.getQuantityVal()||isNaN(this.getQuantityVal())?(a=!1,CommonLibrary.showError(this.$quantity_error,"Quantity should be at least 1")):CommonLibrary.hideError(this.$quantity_error);return a};EditPost.prototype.initWidgetEvents=function(){this.cancel_event_=new CustomEvent(this.EVENTS.EDIT_POST_CANCEL)};EditPost.prototype.EVENTS={EDIT_POST_CANCEL:"edit-post-cancel"};EditPost.prototype.triggerCancelEvent=function(){this.$root.trigger(this.EVENTS.EDIT_POST_CANCEL)};
EditPost.prototype.getTitleVal=function(){return this.$title.val()};EditPost.prototype.getDescriptionVal=function(){return this.$description.html()};EditPost.prototype.getTagsVal=function(){return this.$tags.val()};EditPost.prototype.getQuantityVal=function(){var a=this.$quantity.val();null===a&&(a=0);return parseInt(a)};EditPost.prototype.disableButton=function(){this.$edit.addClass("disabled")};EditPost.prototype.enableButton=function(){this.$edit.removeClass("disabled")};var EmailRegistration=function(a){this.$root=a;this.id=a.data("id");this.resend_resend_loading=this.$resend_resend_loading=this.$resend_cancel_button=this.$resend_resend_button=this.$resend_captcha_error=this.$resend_captcha_field=this.$validation_resend_view=this.$validation_email_view=this.$registration_confirm_password_error=this.$registration_password_error=this.$registration_email_error=this.$registration_save=this.registration_loading=this.$registration_loading=this.$registration_confirm_password=
this.$registration_password=this.$registration_email=this.$validated_area=this.$resend_area=this.$validation_area=this.$registration_area=null;this.init();this.initEvents()};
EmailRegistration.prototype.init=function(){this.$registration_area=this.$root.find(".email-registration-registration");this.$validation_area=this.$root.find(".email-registration-validation");this.$resend_area=this.$root.find(".email-registration-resend");this.$validated_area=this.$root.find(".email-registration-validated");this.$registration_email=this.$root.find(".email-registration-registration-email");this.$registration_password=this.$root.find(".email-registration-registration-password");this.$registration_confirm_password=
this.$root.find(".email-registration-registration-confirm-password");this.$registration_loading=this.$root.find("#"+this.id+"-registration-loading");this.registration_loading=new Loading(this.$registration_loading);this.$registration_save=this.$root.find(".email-registration-registration-save");this.$registration_email_error=this.$root.find(".email-registration-registration-email-error");this.$registration_password_error=this.$root.find(".email-registration-registration-password-error");this.$registration_confirm_password_error=
this.$root.find(".email-registration-registration-confirm-password-error");this.$validation_email_view=this.$root.find(".email-registration-validation-email");this.$validation_resend_view=this.$root.find(".email-registration-validation-resend-view");this.$resend_captcha_field=this.$root.find(".email-registration-resend-captcha");this.$resend_captcha_error=this.$root.find(".email-registration-resend-captcha-error");this.$resend_resend_button=this.$root.find(".email-registration-resend-resend");this.$resend_cancel_button=
this.$root.find(".email-registration-resend-cancel");this.$resend_resend_loading=this.$root.find("#"+this.id+"-resend-loading");this.resend_resend_loading=new Loading(this.$resend_resend_loading)};
EmailRegistration.prototype.initEvents=function(){this.$registration_save.click(function(a){this.validateRegistrationClient()&&this.validateRegistrationServer()}.bind(this));this.$validation_resend_view.click(function(a){this.$resend_area.removeClass("hide");this.$validation_area.addClass("hide")}.bind(this));this.$resend_resend_button.click(function(a){this.validateResendInServer()}.bind(this));this.$resend_cancel_button.click(function(a){this.$resend_area.addClass("hide");this.$validation_area.removeClass("hide")}.bind(this))};
EmailRegistration.prototype.validateResendInServer=function(){this.resend_resend_loading.show();$.ajax({url:$("#base-url").val()+"/site/resend-validation-email",type:"post",data:{email:this.getValidationEmailView(),captcha:this.getResendCaptcha()},context:this,success:function(a){a=JSON.parse(a);0===a.status?void 0!==a.error&&void 0!==a.error.captcha&&CommonLibrary.showError(this.$resend_captcha_error,a.error.captcha[0]):(CommonLibrary.hideError(this.$resend_captcha_error),this.$resend_cancel_button.click());
this.resend_resend_loading.hide()},error:function(a){this.resend_resend_loading.hide()}})};
EmailRegistration.prototype.validateRegistrationServer=function(){this.registration_loading.show();$.ajax({url:$("#base-url").val()+"/site/register-login-user-email",type:"post",context:this,data:{email:this.getEmailRegistration(),password:this.getPasswordRegistration()},success:function(a){a=JSON.parse(a);0===a.status?(void 0!==a.error.email&&CommonLibrary.showError(this.$registration_email_error,a.error.email[0]),void 0!==a.error.password&&CommonLibrary.showError(this.$registration_email_error,
a.error.password[0])):(this.$registration_area.addClass("hide"),this.$validation_area.removeClass("hide"),this.setValidationEmailView(this.getEmailRegistration()),CommonLibrary.hideError(this.$registration_email_error),CommonLibrary.hideError(this.$registration_password_error),CommonLibrary.hideError(this.$registration_confirm_password_error));this.registration_loading.hide()},error:function(a){this.registration_loading.hide()}})};
EmailRegistration.prototype.validateRegistrationClient=function(){var a=!0,b=this.getEmailRegistration(),c=this.getPasswordRegistration(),d=this.getConfirmPasswordRegistration();null===b||""===b?(a=!1,CommonLibrary.showError(this.$registration_email_error,"Email should not be empty")):CommonLibrary.validateEmail(b)?CommonLibrary.hideError(this.$registration_email_error):(a=!1,CommonLibrary.showError(this.$registration_email_error,"Email is not valid"));null===c||""===c?(a=!1,CommonLibrary.showError(this.$registration_password_error,
"Password should not be empty")):6>c.length?(a=!1,CommonLibrary.showError(this.$registration_password_error,"Password should be at least 6 characters")):CommonLibrary.hideError(this.$registration_password_error);d!==c?(a=!1,CommonLibrary.showError(this.$registration_confirm_password_error,"Password does not match")):CommonLibrary.hideError(this.$registration_confirm_password_error);return a};EmailRegistration.prototype.getEmailRegistration=function(){return this.$registration_email.val()};
EmailRegistration.prototype.getPasswordRegistration=function(){return this.$registration_password.val()};EmailRegistration.prototype.getConfirmPasswordRegistration=function(){return this.$registration_confirm_password.val()};EmailRegistration.prototype.getValidationEmailView=function(){return $(this.$validation_email_view[0]).text().trim()};EmailRegistration.prototype.setValidationEmailView=function(a){this.$validation_email_view.text(a)};EmailRegistration.prototype.getResendCaptcha=function(){return this.$resend_captcha_field.val()};
EmailRegistration.prototype.refreshCaptcha=function(){};var HomeProposalBox=function(a){this.$root=a;this.id=a.data("id");this.proposal_sent_event_=null;this.stuff_id=a.data("stuff-id");this.post_link=a.data("post-link");this.loading_area_class=this.send_button_class=this.text_area_class=null;this.init();this.initEvents();this.initWidgetEvents()};HomeProposalBox.prototype.EVENT={HOME_PROPOSAL_BOX_PROPOSAL_SENT:"home-proposal-box-proposal-sent"};
HomeProposalBox.prototype.init=function(){this.text_area_class="home-proposal-box-text-area";this.send_button_class="home-proposal-box-send-button";this.loading_area_class="home-proposal-box-loading-area"};HomeProposalBox.prototype.initWidgetEvents=function(){this.proposal_sent_event_=new CustomEvent(HomeProposalBox.prototype.EVENT.HOME_PROPOSAL_BOX_PROPOSAL_SENT)};
HomeProposalBox.prototype.initEvents=function(){$(document).on("input","#"+this.id,function(a){a.target&&$(a.target).hasClass(this.text_area_class)&&this.inputTextArea_()}.bind(this));$(document).on("click","#"+this.id,function(a){a.target&&$(a.target).hasClass(this.send_button_class)&&this.sendButton_()}.bind(this))};
HomeProposalBox.prototype.sendButton_=function(){var a=this.getTextAreaVal();if(null===a||""===a)return!1;this.showLoading();$.ajax({url:$("#base-url").val()+"/post/send-bid",data:{stuff_id:this.stuff_id,message:a},type:"post",context:this,success:function(a){1===JSON.parse(a).status&&this.triggerProposalSentEvent_();this.hideLoading()}})};HomeProposalBox.prototype.inputTextArea_=function(){var a=this.getTextAreaVal().trim();null===a||""===a?this.disableButton():this.enableButton()};
HomeProposalBox.prototype.triggerProposalSentEvent_=function(){$("#"+this.id).trigger(this.EVENT.HOME_PROPOSAL_BOX_PROPOSAL_SENT,[this.post_link])};HomeProposalBox.prototype.getTextAreaVal=function(){return $("#"+this.id).find("."+this.text_area_class).val()};HomeProposalBox.prototype.showLoading=function(){$("#"+this.id).find("."+this.loading_area_class).removeClass("hide")};HomeProposalBox.prototype.hideLoading=function(){$("#"+this.id).find("."+this.loading_area_class).addClass("hide")};
HomeProposalBox.prototype.enableButton=function(){$("#"+this.id).find("."+this.send_button_class).attr("disabled",!1)};HomeProposalBox.prototype.disableButton=function(){$("#"+this.id).find("."+this.send_button_class).attr("disabled",!0)};var ImageViewEditor=function(a){this.$root=a;this.id=a.data("id");this.image_view_modal_id=this.image_view_image_in_modal_class=this.image_class=null;this.init();this.initEvents()};ImageViewEditor.prototype.init=function(){this.image_class="image-view-editor-image";this.image_view_image_in_modal_class="image-view-editor-image-modal";this.image_view_modal_id=this.id+"-modal"};
ImageViewEditor.prototype.initEvents=function(){$(document).on("click","#"+this.id,function(a){a.target&&$(a.target).hasClass(this.image_class)&&$("#"+this.id).find("#"+this.image_view_modal_id).modal("show").load($(this).attr("value"))}.bind(this))};ImageViewEditor.prototype.setImage=function(a){$("#"+this.id).find("."+this.image_class).attr("src",a);$("#"+this.id).find("."+this.image_view_image_in_modal_class).attr("src",a)};var LinkDropdown=function(a){this.$root=a;this.$dropdown_item=this.$dropdown_button=this.$dropdown_area=null;this.init();this.initEvent()};LinkDropdown.prototype.init=function(){this.$dropdown_area=this.$root.find(".link-dropdown-area");this.$dropdown_button=this.$root.find(".link-dropdown-button");this.$dropdown_item=this.$root.find(".link-dropdown-item")};
LinkDropdown.prototype.initEvent=function(){var a=this;this.$dropdown_button.on("click",function(b){a.$dropdown_area.toggle(100)});this.$dropdown_button.on("blur",function(b){a.$dropdown_area.hide(100)});this.$dropdown_item.on("mousedown",function(a){this.click()})};var Loading=function(a){this.$root=a;this.$loading=null;this.init();this.initEvents()};Loading.prototype.init=function(){this.$loading=this.$root.find(".loading-img")};Loading.prototype.initEvents=function(){};Loading.prototype.hide=function(){this.$root.hide()};Loading.prototype.show=function(){this.$root.show()};Loading.prototype.setMessage=function(a){this.$root.html(a+this.$root.html())};var Login=function(a){this.$root=a;this.id=a.data("id");this.$login_with_facebook=this.$forgot_password_validated=this.forgot_password_loading=this.$forgot_password_loading=this.$forgot_password_submit=this.$forgot_password_captcha_error=this.$forgot_password_email_error=this.$forgot_password_email_field=this.$forgot_password_captcha_field=this.$register_password_error=this.$register_email_error=this.$register_first_name_error=this.$login_password_error=this.$login_email_error=this.$login_password_field=
this.$login_email_field=this.$register_password_field=this.$register_email_field=this.$register_last_name_field=this.$register_first_name_field=this.$login_login_button=this.$login_register_button=this.$forgot_password_panel=this.$register_panel=this.$login_panel=this.$go_to_login_button=this.$register_with_email_button=null;this.country;this.country_code;this.city;this.init();this.initEvents()};
Login.prototype.init=function(){this.$register_with_email_button=this.$root.find(".login-login-register-email");this.$login_panel=this.$root.find(".login-login");this.$register_panel=this.$root.find(".login-register");this.$forgot_password_panel=this.$root.find(".login-forgot-password");this.$go_to_login_button=this.$root.find(".login-register-login");this.$go_to_forgot_password=this.$root.find(".login-login-forgot-password");this.$login_register_button=this.$root.find(".login-register-button");this.$login_login_button=
this.$root.find(".login-login-button");this.$register_first_name_field=this.$root.find(".login-register-first-name");this.$register_last_name_field=this.$root.find(".login-register-last-name");this.$register_email_field=this.$root.find(".login-register-email");this.$register_password_field=this.$root.find(".login-register-password");this.$login_email_field=this.$root.find(".login-login-email");this.$login_password_field=this.$root.find(".login-login-password");this.$forgot_password_captcha_field=
this.$root.find("#"+this.id+"-forgot-password-captcha");this.$forgot_password_email_field=this.$root.find(".login-forgot-password-email");this.$forgot_password_email_error=this.$root.find(".login-forgot-password-email-error");this.$forgot_password_captcha_error=this.$root.find(".login-forgot-password-captcha-error");this.$forgot_password_submit=this.$root.find(".login-forgot-password-button");this.$forgot_password_loading=this.$root.find("#"+this.id+"-forgot-password-loading");this.forgot_password_loading=
new Loading(this.$forgot_password_loading);this.$forgot_password_validated=this.$root.find(".login-forgot-password-validated");this.$login_email_error=this.$root.find(".login-login-email-error");this.$login_password_error=this.$root.find(".login-login-password-error");this.$register_first_name_error=this.$root.find(".login-register-first-name-error");this.$register_email_error=this.$root.find(".login-register-email-error");this.$register_password_error=this.$root.find(".login-register-password-error");
this.$login_with_facebook=this.$root.find(".login-continue-with-facebook")};
Login.prototype.initEvents=function(){this.$register_with_email_button.click(function(a){this.triggerRegisterEvent();this.$register_panel.removeClass("hide");this.$forgot_password_panel.addClass("hide");this.$login_panel.addClass("hide")}.bind(this));this.$go_to_login_button.click(function(a){this.triggerLoginEvent();this.$register_panel.addClass("hide");this.$forgot_password_panel.addClass("hide");this.$login_panel.removeClass("hide")}.bind(this));this.$go_to_forgot_password.click(function(a){this.triggerForgotPasswordEvent();
this.$register_panel.addClass("hide");this.$login_panel.addClass("hide");this.$forgot_password_panel.removeClass("hide")}.bind(this));this.$forgot_password_submit.click(function(a){this.submitForgotPasswordForm()}.bind(this));this.$login_register_button.click(function(a){this.submitRegisterForm()}.bind(this));this.$login_login_button.click(function(a){this.submitLoginForm()}.bind(this));this.$login_with_facebook.click(function(a){$.ajax({url:$("#base-url").val()+"/site/auth?authclient=facebook",type:"post",
context:this,data:{country_code:this.country_code,country:this.country,city:this.city},success:function(a){}})}.bind(this));this.$login_panel.on("keypress",function(a){13===a.keyCode&&this.submitLoginForm()}.bind(this));this.$register_panel.on("keypress",function(a){13===a.keyCode&&this.submitRegisterForm()}.bind(this))};Login.prototype.submitForgotPasswordForm=function(){($valid=this.validateForgotPasswordFormInClient())&&this.validateForgotPasswordFormInServer()};
Login.prototype.submitRegisterForm=function(){($valid=this.validateRegisterFormInClient())&&this.validateRegisterInServerSide()};Login.prototype.submitLoginForm=function(){($valid=this.validateLoginFormInClient())&&this.validateLoginInServerSide()};
Login.prototype.validateForgotPasswordFormInClient=function(){var a=!0,b=this.getForgotPasswordEmailField(),c=this.getForgotPasswordCaptchaField();null===b||""===b?(a=!1,CommonLibrary.showError(this.$forgot_password_email_error,"Email address must not be empty")):CommonLibrary.hideError(this.$forgot_password_email_error);null===c||""===c?(a=!1,CommonLibrary.showError(this.$forgot_password_captcha_error,"Captcha should not be empty")):CommonLibrary.hideError(this.$forgot_password_captcha_error);return a};
Login.prototype.validateForgotPasswordFormInServer=function(){this.forgot_password_loading.show();$.ajax({url:$("#base-url").val()+"/site/request-password-reset",type:"post",context:this,data:{email:this.getForgotPasswordEmailField(),captcha:this.getForgotPasswordCaptchaField()},success:function(a){a=JSON.parse(a);1===a.status?(CommonLibrary.hideError(this.$forgot_password_email_error),CommonLibrary.hideError(this.$forgot_password_captcha_error),this.$forgot_password_submit.addClass("hide"),this.$forgot_password_validated.removeClass("hide")):
(a=a.error,void 0!==a.email&&CommonLibrary.showError(this.$forgot_password_email_error,a.email[0]),void 0!==a.captcha&&CommonLibrary.showError(this.$forgot_password_captcha_error,a.captcha[0]));this.forgot_password_loading.hide()},error:function(a){this.forgot_password_loading.hide()}})};
Login.prototype.validateLoginFormInClient=function(){var a=!0,b=this.getLoginEmailField(),c=this.getLoginPasswordField();null===b||""===b?(a=!1,this.showLoginEmailErrorMsg("Email address must not be empty")):this.hideLoginEmailErrorMsg();null===c||""===c?(a=!1,this.showLoginPasswordErrorMsg("Password field must not be empty")):this.hideLoginPasswordErrorMsg();return a};
Login.prototype.validateLoginInServerSide=function(){CommonLibrary.showCommonLoading();$.ajax({url:$("#base-url").val()+"/site/login",type:"post",context:this,data:{email:this.getLoginEmailField(),password:this.getLoginPasswordField(),redirect:window.location.href},success:function(a){a=JSON.parse(a);0===a.status?"email"in a.message?this.showLoginEmailErrorMsg(a.message.email[0]):this.showLoginPasswordErrorMsg(a.message.password[0]):(this.hideLoginEmailErrorMsg(),this.hideLoginPasswordErrorMsg());
CommonLibrary.hideCommonLoading()}})};
Login.prototype.validateRegisterInServerSide=function(){CommonLibrary.showCommonLoading();$.ajax({url:$("#base-url").val()+"/site/signup",type:"post",context:this,data:{first_name:this.getRegisterFirstNameField(),last_name:this.getRegisterLastNameField(),email:this.getRegisterEmailField(),password:this.getRegisterPasswordField()},success:function(a){a=JSON.parse(a);0===a.status?"email"in a.message&&this.showRegisterEmailErrorMsg(a.message.email[0]):this.hideRegisterEmailErrorMsg();CommonLibrary.hideCommonLoading()}})};
Login.prototype.validateRegisterFormInClient=function(){$valid=!0;var a=this.getRegisterFirstNameField();this.getRegisterLastNameField();var b=this.getRegisterEmailField(),c=this.getRegisterPasswordField();null===a||""===a?($valid=!1,this.showRegisterFirstNameErrorMsg("First name should not be empty")):this.hideRegisterFirstNameErrorMsg();CommonLibrary.validateEmail(b)?this.hideRegisterEmailErrorMsg():($valid=!1,this.showRegisterEmailErrorMsg("Email address is not valid"));6>c.length?($valid=!1,this.showRegisterPasswordErrorMsg("Password should be at least 6 characters")):
this.hideRegisterPasswordErrorMsg();return $valid};Login.prototype.getRegisterFirstNameField=function(){return this.$register_first_name_field.val()};Login.prototype.getRegisterLastNameField=function(){return this.$register_last_name_field.val()};Login.prototype.getRegisterEmailField=function(){return this.$register_email_field.val()};Login.prototype.getRegisterPasswordField=function(){return this.$register_password_field.val()};Login.prototype.getLoginEmailField=function(){return this.$login_email_field.val()};
Login.prototype.getLoginPasswordField=function(){return this.$login_password_field.val()};Login.prototype.getForgotPasswordEmailField=function(){return this.$forgot_password_email_field.val()};Login.prototype.getForgotPasswordCaptchaField=function(){return this.$forgot_password_captcha_field.val()};Login.prototype.showRegisterFirstNameErrorMsg=function(a){this.$register_first_name_error.html(a)};Login.prototype.hideRegisterFirstNameErrorMsg=function(){this.$register_first_name_error.html("")};
Login.prototype.showRegisterEmailErrorMsg=function(a){this.$register_email_error.html(a)};Login.prototype.hideRegisterEmailErrorMsg=function(){this.$register_email_error.html("")};Login.prototype.showRegisterPasswordErrorMsg=function(a){this.$register_password_error.html(a)};Login.prototype.hideLoginEmailErrorMsg=function(){this.$login_email_error.html("")};Login.prototype.hideLoginPasswordErrorMsg=function(){this.$login_password_error.html("")};Login.prototype.showLoginEmailErrorMsg=function(a){this.$login_email_error.html(a)};
Login.prototype.showLoginPasswordErrorMsg=function(a){this.$login_password_error.html(a)};Login.prototype.hideRegisterPasswordErrorMsg=function(){this.$register_password_error.html("")};Login.prototype.EVENTS={LOGIN_LOGIN:"login-login",LOGIN_FORGOT_PASSWORD:"login-forgot-password",LOGIN_REGISTER:"login-register"};Login.prototype.triggerLoginEvent=function(){this.$root.trigger(this.EVENTS.LOGIN_LOGIN)};Login.prototype.triggerRegisterEvent=function(){this.$root.trigger(this.EVENTS.LOGIN_REGISTER)};
Login.prototype.triggerForgotPasswordEvent=function(){this.$root.trigger(this.EVENTS.LOGIN_FORGOT_PASSWORD)};var NotificationItem=function(a){this.$root=a;this.id=a.data("id");this.url=a.data("url");this.notification_id=a.data("notification_id");this.click_event_=null;this.init();this.initEvents();this.initWidgetEvents()};NotificationItem.prototype.initEvents=function(){$(document).on("click","#"+this.id,function(a){window.location.href=$("#base-url").val()+"/"+this.url;this.sendReadStatus();this.triggerClick();this.removeBlueBackground()}.bind(this))};
NotificationItem.prototype.removeBlueBackground=function(){$("#"+this.id).removeClass("notification-item-not-read")};NotificationItem.prototype.initWidgetEvents=function(){this.click_event_=new CustomEvent(this.EVENTS.NOTIFICATION_ITEM_CLICK)};NotificationItem.prototype.sendReadStatus=function(){$.ajax({url:$("#base-url").val()+"/notification/set-unread",type:"post",data:{notification_id:this.notification_id},success:function(a){JSON.parse(a)}})};NotificationItem.prototype.init=function(){};
NotificationItem.prototype.EVENTS={NOTIFICATION_ITEM_CLICK:"notification_item_click"};NotificationItem.prototype.triggerClick=function(){this.$root.trigger(this.EVENTS.NOTIFICATION_ITEM_CLICK)};var NotificationList=function(a){this.$root=a;this.id=a.data("id");this.$notif_count=this.$notif_list_items_area=this.$notif_list_area=this.$retrieve_button=this.retrieve_loading=this.$retrieve_loading=null;this.has_retrieved=!1;this.$no_more=this.$see_all_button=null;this.notification_items=[];this.init();this.initEvents()};
NotificationList.prototype.init=function(){this.$retrieve_loading=this.$root.find("#"+this.id+"-loading-retrieve-notif");this.retrieve_loading=new Loading(this.$retrieve_loading);this.$retrieve_button=this.$root.find(".notification-list-retrieve-button");this.$notif_list_area=this.$root.find(".notification-list-area");this.$notif_list_items_area=this.$root.find(".notification-list-items-area");this.$no_more=this.$root.find(".notification-list-no-more-notification");this.$notif_count=this.$root.find(".notification-list-count");
this.$see_all_button=this.$root.find(".notification-list-see-all-button");this.countNewNotif()};NotificationList.prototype.countNewNotif=function(){$.ajax({url:$("#base-url").val()+"/notification/count-new-notification",type:"post",context:this,success:function(a){a=JSON.parse(a);1===a.status&&0!==parseInt(a.count)&&this.setCount(a.count)}})};
NotificationList.prototype.updateLastSeen=function(){$.ajax({url:$("#base-url").val()+"/notification/update-last-seen",type:"post",context:this,success:function(a){1===JSON.parse(a).status&&this.removeCount()}})};
NotificationList.prototype.retrieveNotification=function(){this.retrieve_loading.show();this.has_retrieved=!0;$.ajax({url:$("#base-url").val()+"/notification/retrieve-notification",type:"post",context:this,success:function(a){a=JSON.parse(a);1===a.status&&(""===a.views||null===a.views?this.$no_more.removeClass("hide"):(this.$notif_list_items_area.html(a.views),$(a.views).filter(".notification-item").each(function(a,c){this.notification_items.push(new NotificationItem($(c)))}.bind(this))));this.retrieve_loading.hide()},
error:function(a){this.retrieve_loading.hide()}})};
NotificationList.prototype.initEvents=function(){this.$retrieve_button.click(function(){this.$notif_list_area.hasClass("hide")?this.$notif_list_area.removeClass("hide"):this.$notif_list_area.addClass("hide");this.updateLastSeen();this.has_retrieved||this.retrieveNotification()}.bind(this));$("body").on("click",function(a){a.target&&0===$(a.target).closest("#"+this.id).length&&this.$notif_list_area.addClass("hide")}.bind(this));$(document).on("click","#"+this.id,function(a){a.target&&0!==$(a.target).closest(".notification-item").length&&
this.$notif_list_area.addClass("hide")}.bind(this))};NotificationList.prototype.setCount=function(a){$(this.$retrieve_button).addClass("notification-list-count");$(this.$retrieve_button).html(""+a)};NotificationList.prototype.removeCount=function(){$(this.$retrieve_button).removeClass("notification-list-count");this.$retrieve_button.html('<span class="glyphicon glyphicon-bell"></span>')};var PostCard=function(a){this.$root=a;this.stuff_id=this.$root.data("stuff_id");this.id=this.$root.data("id");this.is_owner=this.$root.data("is_owner");this.post_link=this.$root.data("post_link");this.$proposal_box=this.proposal_box=this.image_view_editor=this.$image_view_editor=this.post_view_class=this.proposal_box_class=this.proposal_box_modal_class=this.total_favorite_class=this.favorite_button_class=this.propose_button_class=null;this.init();this.initEvents()};
PostCard.prototype.init=function(){this.propose_button_class="post-card-button-propose";this.proposal_box_modal_class="post-card-proposal-box-modal";this.favorite_button_class="post-card-button-favorite";this.total_favorite_class="post-card-total-favorite";this.proposal_box_class="home-proposal-box-container";this.image_view_editor_id=this.id+"-image-view";this.post_view_class="post-card-view";this.$image_view_editor=this.$root.find("#"+this.image_view_editor_id);this.image_view_editor=new ImageViewEditor(this.$image_view_editor);
this.$proposal_box=this.$root.find("."+this.proposal_box_class);this.proposal_box=new HomeProposalBox(this.$proposal_box)};
PostCard.prototype.initEvents=function(){$(document).on("click","#"+this.id,function(a){if(a.target&&$(a.target).hasClass(this.propose_button_class)){if(this.is_owner||CommonLibrary.isGuest())return!1;$("#"+this.id).find("."+this.proposal_box_modal_class).modal("show").load($(this).attr("value"))}else a.target&&$(a.target).hasClass(this.favorite_button_class)&&this.clickFavoriteButton_();a.target&&0!==$(a.target).closest("."+this.post_view_class).length&&(window.location.href=this.post_link)}.bind(this));
$(document).on(HomeProposalBox.prototype.EVENT.HOME_PROPOSAL_BOX_PROPOSAL_SENT,"#"+this.id,function(a,b){a.target&&$(a.target).hasClass(this.proposal_box_class)&&(window.location.href=b)}.bind(this))};
PostCard.prototype.clickFavoriteButton_=function(){if(CommonLibrary.isGuest())return!1;this.hasFavorited()?(this.unmarkFavorite(),this.decreaseFavorite(),$.ajax({url:$("#base-url").val()+"/post/cancel-favorite",type:"post",context:this,data:{stuff_id:this.stuff_id},success:function(a){0===JSON.parse(a).status&&this.increaseFavorite()}})):(this.markFavorite(),this.increaseFavorite(),$.ajax({url:$("#base-url").val()+"/post/request-favorite",type:"post",data:{stuff_id:this.stuff_id},success:function(a){0===
JSON.parse(a).status&&this.decreaseFavorite()}}))};PostCard.prototype.increaseFavorite=function(){var a=this.getTotalFavorite();this.setTotalFavorite(a+1)};PostCard.prototype.decreaseFavorite=function(){var a=this.getTotalFavorite();this.setTotalFavorite(a-1)};PostCard.prototype.markFavorite=function(){$("#"+this.id).find("."+this.favorite_button_class).addClass("post-card-button-red")};PostCard.prototype.unmarkFavorite=function(){$("#"+this.id).find("."+this.favorite_button_class).removeClass("post-card-button-red")};
PostCard.prototype.setTotalFavorite=function(a){$("#"+this.id).find("."+this.total_favorite_class).html(a)};PostCard.prototype.getTotalFavorite=function(){return parseInt($("#"+this.id).find("."+this.total_favorite_class).html())};PostCard.prototype.hasFavorited=function(){return $("#"+this.id).find("."+this.favorite_button_class).hasClass("post-card-button-red")};var PostCommentContainer=function(a){this.$root=a;this.id=a.data("id");this.post_id=a.data("post_id");this.post_comment_area_class=this.post_comment_class=this.text_area_error_class=this.text_area_id=this.submit_comment_class=null;this.post_comments=[];this.init();this.initEvents()};
PostCommentContainer.prototype.init=function(){this.submit_comment_class="post-comment-container-submit-comment";this.text_area_id=this.id+"-text-area";this.text_area_error_class="post-comment-container-text-box-error";this.post_comment_area_class="post-comment-container-area";this.post_comment_class="post-comment";$.each($("#"+this.id).find(".post-comment"),function(a,b){this.post_comments.push(new PostComment($(b)))}.bind(this))};
PostCommentContainer.prototype.initEvents=function(){$(document).on("click","#"+this.id,function(a){if(a.target&&$(a.target).hasClass(this.submit_comment_class)){if(CommonLibrary.isGuest())return!1;this.submitComment()}}.bind(this));$(document).on("focus","#"+this.id,function(a){if(a.target&&$(a.target).attr("id")===this.text_area_id&&CommonLibrary.isGuest())return!1}.bind(this));$(document).on(PostComment.prototype.EVENTS.POST_COMMENT_DELETE_EVENT,"#"+this.id,function(a,b){a.target&&$(a.target).hasClass(this.post_comment_class)}.bind(this));
$(document).on(PostComment.prototype.EVENTS.POST_COMMENT_REPLY_EVENT,"#"+this.id,function(a,b){a.target&&$(a.target).hasClass(this.post_comment_class)&&this.appendValueToTextArea("<a href='"+b.user_link+"'>"+b.full_name+"</a>")}.bind(this))};
PostCommentContainer.prototype.submitComment=function(){$valid=this.validateClient();!1!==$valid&&(this.disableSubmitButton(),$.ajax({url:$("#base-url").val()+"/post-comment/create",type:"post",context:this,data:{message:this.getTextAreaVal(),post_id:this.post_id},success:function(a){a=JSON.parse(a);this.prependToItemArea(a.view);this.post_comments.push(new PostComment($(a.view)));this.setTextAreaToNull();this.enableSubmitButton()}}))};
PostCommentContainer.prototype.validateClient=function(){$valid=!0;null===this.getTextAreaVal()||""===this.getTextAreaVal()?(CommonLibrary.showError($("#"+this.id).find("."+this.text_area_error_class),"Text box cannot be empty"),$valid=!1):CommonLibrary.hideError($("#"+this.id).find("."+this.text_area_error_class));return $valid};PostCommentContainer.prototype.getTextAreaVal=function(){return $("#"+this.id).find("#"+this.text_area_id).html()};
PostCommentContainer.prototype.setTextAreaToNull=function(){return $("#"+this.id).find("#"+this.text_area_id).html("")};PostCommentContainer.prototype.appendValueToTextArea=function(a){return $("#"+this.id).find("#"+this.text_area_id).append(a)};PostCommentContainer.prototype.enableSubmitButton=function(){$("#"+this.id).find("."+this.submit_comment_class).removeClass("disabled")};PostCommentContainer.prototype.disableSubmitButton=function(){$("#"+this.id).find("."+this.submit_comment_class).addClass("disabled")};
PostCommentContainer.prototype.prependToItemArea=function(a){$("#"+this.id).find("."+this.post_comment_area_class).prepend(a)};var PostComment=function(a){this.$root=a;this.id=a.data("id");this.comment_id=a.data("comment_id");this.user_link=a.data("user_link");this.full_name=a.data("full_name");this.reply_event_=this.delete_event_=this.view_area_class=this.edit_text_area_class=this.edit_area_class=this.delete_class=this.cancel_edit_class=this.send_edit_class=this.edit_class=this.reply_class=null;this.init();this.initEvents();this.initWidgetEvents()};
PostComment.prototype.init=function(){this.reply_class="post-comment-reply";this.edit_class="post-comment-edit";this.send_edit_class="post-comment-message-edit-button";this.cancel_edit_class="post-comment-message-cancel-button";this.delete_class="post-comment-delete";this.edit_text_area_class="post-comment-message-edit-text";this.edit_area_class="post-comment-message-edit";this.view_area_class="post-comment-message"};
PostComment.prototype.initEvents=function(){$(document).on("click","#"+this.id,function(a){a.target&&$(a.target).hasClass(this.delete_class)?ConfirmationModal.show("Are you sure you want to delete this comment?",function(a){a&&this.deleteComment()}.bind(this)):a.target&&$(a.target).hasClass(this.reply_class)?this.triggerReplyEvent({user_link:this.user_link,full_name:this.full_name}):a.target&&$(a.target).hasClass(this.edit_class)?($("#"+this.id).find("."+this.edit_area_class).removeClass("hide"),
$("#"+this.id).find("."+this.view_area_class).addClass("hide")):a.target&&$(a.target).hasClass(this.cancel_edit_class)?this.cancelEditComment():a.target&&$(a.target).hasClass(this.send_edit_class)&&this.sendEditComment()}.bind(this))};PostComment.prototype.cancelEditComment=function(){$("#"+this.id).find("."+this.edit_area_class).addClass("hide");$("#"+this.id).find("."+this.view_area_class).removeClass("hide")};
PostComment.prototype.sendEditComment=function(){null===this.getTextAreaText()||""===this.getTextAreaText()?this.cancelEditComment():(this.setViewMessage(this.getTextAreaHtml()),this.cancelEditComment(),$.ajax({url:$("#base-url").val()+"/post-comment/edit",type:"post",context:this,data:{comment_id:this.comment_id,message:this.getTextAreaHtml()},success:function(a){}}))};PostComment.prototype.getTextAreaText=function(){return $("#"+this.id).find("."+this.edit_text_area_class).text()};
PostComment.prototype.getTextAreaHtml=function(){return $("#"+this.id).find("."+this.edit_text_area_class).html()};PostComment.prototype.setViewMessage=function(a){$("#"+this.id).find("."+this.view_area_class).html(a)};PostComment.prototype.initWidgetEvents=function(){this.delete_event_=new CustomEvent(this.EVENTS.POST_COMMENT_DELETE_EVENT);this.reply_event_=new CustomEvent(this.EVENTS.POST_COMMENT_REPLY_EVENT)};
PostComment.prototype.deleteComment=function(){$.ajax({url:$("#base-url").val()+"/post-comment/delete",type:"post",context:this,data:{comment_id:this.comment_id},success:function(a){1===JSON.parse(a).status&&$("#"+this.id).remove()}})};PostComment.prototype.EVENTS={POST_COMMENT_DELETE_EVENT:"post-comment-delete-event",POST_COMMENT_REPLY_EVENT:"post-comment-reply-event"};PostComment.prototype.triggerDeleteEvent=function(a){return this.$root.trigger(this.EVENTS.POST_COMMENT_DELETE_EVENT,[a])};
PostComment.prototype.triggerReplyEvent=function(a){return $("#"+this.id).trigger(this.EVENTS.POST_COMMENT_REPLY_EVENT,[a])};var PostList=function(a){this.$root=a;this.stuff_ids="";this.id=a.data("id");this.location=a.data("location");this.query="";this.tags=[];this.post_cards=[];this.$post_list_area=null;this.permit_retrieve_post=!0;this.$reached_the_end=this.get_more_loading=this.$get_more_loading=this.new_loading=this.$new_loading=null;this.is_retrieving=!1;this.init();this.initEvents()};PostList.prototype.SCROLL_VALUE=95;
PostList.prototype.init=function(){$.each($(".post-card"),function(a,b){this.post_cards.push(new PostCard($(b)));this.stuff_ids=""===this.stuff_ids?this.stuff_ids+$(b).data("stuff_id"):this.stuff_ids+(","+$(b).data("stuff_id"))}.bind(this));this.$new_loading=this.$root.find("#"+this.id+"-new-loading");this.new_loading=new Loading(this.$new_loading);this.$get_more_loading=this.$root.find("#"+this.id+"-get-more-loading");this.get_more_loading=new Loading(this.$get_more_loading);this.$post_list_area=
this.$root.find(".post-list-area");this.$reached_the_end=this.$root.find(".post-list-no-more");this.$post_list_header=this.$root.find(".post-list-header")};PostList.prototype.initEvents=function(){};PostList.prototype.getHeight=function(){return this.$root.height()};PostList.prototype.setNewTags=function(a){this.tags=a;this.searchNewData();this.is_retrieving=!1;this.$reached_the_end.addClass("hide")};
PostList.prototype.setQueryAndLocation=function(a,b){this.query=a;this.location=b;setTimeout(this.searchNewData.bind(this),300);this.is_retrieving=!1;this.$reached_the_end.addClass("hide")};PostList.prototype.stringifyArray=function(a){for(var b="",c=!0,d=0;d<a.length;d++)c?(b+=a[d],c=!1):b+=","+a[d];return b};
PostList.prototype.searchNewData=function(){this.new_loading.show();$("html, body").animate({scrollTop:this.$post_list_header.position().top-100});$.ajax({url:$("#base-url").val()+"/site/search-new-data",type:"post",context:this,data:{query:this.query,location:this.location,tags:this.stringifyArray(this.tags)},success:function(a){a=JSON.parse(a);1===a.status&&(this.$post_list_area.html(a.view),this.post_cards=[],this.stuff_ids="0",$(a.view).filter(".post-card").each(function(a,c){var d=new PostCard($(c));
this.post_cards.push(d);this.stuff_ids+=","+$(c).data("stuff_id")}.bind(this)));this.new_loading.hide()},error:function(a){this.new_loading.hide()}})};
PostList.prototype.getMorePosts=function(){this.is_retrieving||(this.get_more_loading.show(),this.is_retrieving=!0,$.ajax({url:$("#base-url").val()+"/site/get-more-posts",type:"post",context:this,data:{query:this.query,ids:this.stuff_ids,location:this.location,tags:this.stringifyArray(this.tags)},success:function(a){this.is_retrieving=!1;a=JSON.parse(a);1===a.status&&(this.$post_list_area.append(a.view),""===a.view&&(this.is_retrieving=!0,this.$reached_the_end.removeClass("hide")),$(a.view).filter(".post-card").each(function(a,
c){var d=new PostCard($(c));this.post_cards.push(d);this.stuff_ids+=","+$(c).data("stuff_id")}.bind(this)));this.get_more_loading.hide()},error:function(a){this.is_retrieving=!1;this.get_more_loading.hide()}}))};var PostSection=function(a){this.$root=a;this.id=a.data("id");this.stuff_id=a.data("stuff_id");this.$text_area_error=this.$quantity_error=this.$edit_button=this.$delete_button=this.$cancel_favorite_button=this.$request_favorite_button=this.$bid_button=this.$text_area=this.quantity=this.$quantity=null;this.init();this.initEvents()};
PostSection.prototype.init=function(){this.$quantity=this.$root.find("#"+this.id+"-quantity-widget");this.quantity=new QuantityWidget(this.$quantity);this.$text_area=this.$root.find("#"+this.id+"-text-area");this.$bid_button=this.$root.find(".post-section-bid");this.$text_area_error=this.$root.find(".post-section-text-area-section-error");this.$quantity_error=this.$root.find(".post-section-quantity-error");this.$request_favorite_button=this.$root.find(".post-section-request-favorite");this.$cancel_favorite_button=
this.$root.find(".post-section-cancel-favorite");this.$delete_button=this.$root.find(".post-section-owner-delete");this.$edit_button=this.$root.find(".post-section-owner-edit");this.$view=this.$root.find(".post-section-view");this.$edit=this.$root.find(".post-section-edit");this.$edit_post=this.$root.find("#"+this.id+"-edit-post");this.edit_post=new EditPost(this.$edit_post)};
PostSection.prototype.initEvents=function(){this.$edit_post.on(EditPost.prototype.EVENTS.EDIT_POST_CANCEL,function(a){this.$view.removeClass("hide");this.$edit.addClass("hide")}.bind(this));this.$delete_button.click(function(a){ConfirmationModal.show("Are you sure you want to delete this post?",function(a){a&&this.deletePost()}.bind(this))}.bind(this));this.$edit_button.click(function(a){this.$view.addClass("hide");this.$edit.removeClass("hide")}.bind(this));this.$bid_button.click(function(a){if(CommonLibrary.isGuest())return!1;
this.validateInClient()&&this.sendProposal()}.bind(this));this.$request_favorite_button.click(function(a){if(CommonLibrary.isGuest())return!1;$.ajax({url:$("#base-url").val()+"/post/request-favorite",type:"post",data:{stuff_id:this.stuff_id},success:function(a){1===JSON.parse(a).status&&window.location.reload()}})}.bind(this));this.$cancel_favorite_button.click(function(a){$.ajax({url:$("#base-url").val()+"/post/cancel-favorite",type:"post",data:{stuff_id:this.stuff_id},success:function(a){1===JSON.parse(a).status&&
window.location.reload()}})}.bind(this));this.$text_area.on("focus",function(a){if(CommonLibrary.isGuest())return!1}.bind(this))};PostSection.prototype.deletePost=function(){$.ajax({url:$("#base-url").val()+"/post/delete",type:"post",data:{stuff_id:this.stuff_id},success:function(a){1===JSON.parse(a).status&&window.location.reload()}})};
PostSection.prototype.sendProposal=function(){$.ajax({url:$("#base-url").val()+"/bid/send-bid",type:"post",data:{quantity:this.getQuantityVal(),message:this.getTextAreaHtml(),stuff_id:this.stuff_id},success:function(a){1===JSON.parse(a).status&&window.location.reload()}})};
PostSection.prototype.validateInClient=function(){$valid=!0;0===this.getQuantityVal()||isNaN(this.getQuantityVal())?($valid=!1,this.showError(this.$quantity_error,"Quantity should be at least 1")):this.hideError(this.$quantity_error);null===this.getTextAreaText()||""===this.getTextAreaText()?($valid=!1,this.showError(this.$text_area_error,"Please send a sentence to the owner to convince them you deserve this stuff")):this.hideError(this.$text_area_error);return $valid};
PostSection.prototype.getQuantityVal=function(){return this.quantity.getQuantity()};PostSection.prototype.getTextAreaText=function(){return this.$text_area.text()};PostSection.prototype.getTextAreaHtml=function(){return this.$text_area.html()};PostSection.prototype.showError=function(a,b){a.html(b)};PostSection.prototype.hideError=function(a){a.html("")};var Post=function(a){this.$root=a;this.stuff_id=a.data("stuff_id");this.post_comment_container=this.$post_comment_container=this.change_image=this.$change_image=this.$change_image_modal=this.$change_image_button=this.$post_image=this.post_image_view_editor=this.$post_image_view_editor=this.post_section=this.$post_section=this.$bidder_list=this.bidder_list=this.$bid_container=this.bid_container=this.$bid_button=null;this.init();this.initEvents()};
Post.prototype.init=function(){this.$bid_button=this.$root.find("#post-bid-button");this.$bid_container=this.$root.find("#post-bid-containers");this.bid_container=new BidContainer(this.$bid_container);this.$bidder_list=this.$root.find("#bidder-list");this.bidder_list=new BidderList(this.$bidder_list);this.$post_section=this.$root.find("#post-section");this.post_section=new PostSection(this.$post_section);this.$post_image_view_editor=this.$root.find("#image-view-editor");this.post_image_view_editor=
new ImageViewEditor(this.$post_image_view_editor);this.$post_image=this.$root.find(".post-image");this.$change_image_button=this.$root.find(".post-change-image");this.$change_image_modal=this.$root.find("#change-image-modal");this.$change_image=this.$root.find("#change-image");this.change_image=new ChangeImage(this.$change_image);this.$post_comment_container=this.$root.find("#post-comment-container");this.post_comment_container=new PostCommentContainer(this.$post_comment_container)};
Post.prototype.initEvents=function(){var a=this;this.$bid_button.on("click",function(b){a.$proposal_box_modal.modal("show");a.$proposal_box_modal.load($(this).attr("value"))});this.$post_image.hover(function(){this.$change_image_button.removeClass("hide")}.bind(this));this.$post_image.mouseout(function(){this.$change_image_button.is(":hover")||this.$post_image.is(":hover")||this.$change_image_button.addClass("hide")}.bind(this));this.$change_image_button.on("click",function(a){this.$change_image_modal.modal("show").load($(this).attr("value"))}.bind(this));
this.$change_image.on(ChangeImage.prototype.EVENT.CHANGE_IMAGE_CANCEL,function(a,c){this.$change_image_modal.modal("hide")}.bind(this));this.$change_image.on(ChangeImage.prototype.EVENT.CHANGE_IMAGE_IMAGE_CHANGED,function(a,c){this.changeImage(c.image_id);this.post_image_view_editor.setImage(c.image_path);this.$change_image_modal.modal("hide")}.bind(this))};
Post.prototype.changeImage=function(a){$.ajax({url:$("#base-url").val()+"/post/edit-post-image",type:"POST",data:{stuff_id:this.stuff_id,image_id:a},success:function(a){}})};Post.prototype.addBidLayoutByStuffId=function(a){$.ajax({url:$("#base-url").val()+"/bid/get-bid-layout",context:this,data:{stuff_id:a},type:"post",success:function(a){}})};var QuantityWidget=function(a){this.$root=a;this.max_value=a.data("max_value");this.$input=this.$minus_button=this.$plus_button=null;this.init();this.initEvents()};QuantityWidget.prototype.init=function(){this.$plus_button=this.$root.find(".quantity-widget-plus");this.$minus_button=this.$root.find(".quantity-widget-minus");this.$input=this.$root.find(".quantity-widget-number-input")};QuantityWidget.prototype.initEvents=function(){this.$plus_button.click(function(a){this.addOne()}.bind(this));this.$minus_button.click(function(a){this.minusOne()}.bind(this))};
QuantityWidget.prototype.addOne=function(){parseInt(this.$input.val())+1<=this.max_value&&this.$input.val(parseInt(this.$input.val())+1)};QuantityWidget.prototype.minusOne=function(){var a=parseInt(this.$input.val())-1;0<=a&&this.$input.val(a)};QuantityWidget.prototype.getQuantity=function(){return parseInt(this.$input.val())};$(document).ready(function(){String.prototype.replaceAll=function(a,b){return this.replace(new RegExp(a,"g"),b)};Array.prototype.remove=function(a){a=this.indexOf(a);return-1!==a?this.splice(a,1):this};new App($(this))});
var App=function(a){this.$root=a;this.notification_list=this.$notification_list=this.create_post_form=this.$create_post_form=this.$create_post_button=this.$create_post_modal=this.profile_link_dropdown=this.$profile_link_dropdown=this.login_form=this.$home_menu_btn=this.$login_form=this.$login_modal=this.$login_button=this.$post=this.site=this.$site=null;this.init();this.initEvents()};App.prototype.CSS_CLASSES={};
App.prototype.init=function(){0!==this.$root.find(".site-index").length?(this.$site=this.$root.find(".site-index"),this.site=new Site(this.$site)):0!==this.$root.find(".post-index").length?this.$post=new Post(this.$root.find(".post-index")):0!==this.$root.find(".create-post-index").length&&(this.$create_post_form=this.$root.find(".create-post-index"),this.create_post_form=new CreatePost(this.$create_post_form));0!==this.$root.find("#login-menu").length&&(this.$login_button=this.$root.find("#login-menu"),
this.$login_modal=this.$root.find("#login-modal"));this.$home_menu_button=this.$root.find(".home-menu-button");this.$login_form=this.$root.find("#login-form");this.login_form=new Login(this.$login_form);this.$create_post_button=this.$root.find(".give-stuff-modal-button");this.$profile_link_dropdown=this.$root.find("#profile-menu");this.profile_link_dropdown=new LinkDropdown(this.$profile_link_dropdown);this.$create_post_form=this.$root.find("#create-post");this.create_post_form=new CreatePost(this.$create_post_form);
this.$notification_list=this.$root.find("#notification-list");this.notification_list=new NotificationList(this.$notification_list)};
App.prototype.initEvents=function(){this.$create_post_button.click(function(a){window.location.href=$("#base-url").val()+"/post/create"}.bind(this));if(0!==this.$root.find("#login-menu").length){var a=this;this.$login_button.click(function(b){a.$login_modal.modal("show").load($(this).attr("value"))})}this.$home_menu_button.click(function(a){window.location.href=$("#base-url").val()+"/"});this.$login_form.on(Login.prototype.EVENTS.LOGIN_REGISTER,function(a){this.setLoginHeaderModalTitle("Register")}.bind(this));
this.$login_form.on(Login.prototype.EVENTS.LOGIN_LOGIN,function(a){this.setLoginHeaderModalTitle("Login")}.bind(this));this.$login_form.on(Login.prototype.EVENTS.LOGIN_FORGOT_PASSWORD,function(a){this.setLoginHeaderModalTitle("Forgot Password")}.bind(this))};App.prototype.setLoginHeaderModalTitle=function(a){this.$root.find(".login-modal-header").html('<h4 class="login-modal-header" align="center">'+a+"</h4>")};var SearchBar=function(a){this.$root=a;this.id=this.$root.data("id");this.search_event_=this.$search_field=this.$location=null;this.init();this.initEvents();this.initWidgetEvents()};SearchBar.prototype.EVENT={SEARCH_BAR_SEARCH:"search-bar-search"};SearchBar.prototype.init=function(){this.$location=this.$root.find("#"+this.id+"-city");this.$search_field=this.$root.find(".search-bar-input")};
SearchBar.prototype.initEvents=function(){this.$search_field.on("input",function(a){this.triggerSearchEvent({location:this.getLocationValue(),query:this.getQuery()})}.bind(this));this.$location.change(function(a){this.triggerSearchEvent({location:this.getLocationValue(),query:this.getQuery()})}.bind(this))};SearchBar.prototype.initWidgetEvents=function(){this.search_event_=new CustomEvent(SearchBar.prototype.EVENT.SEARCH_BAR_SEARCH)};SearchBar.prototype.getLocationValue=function(){return this.$location.val()};
SearchBar.prototype.getLocationText=function(){return this.$location.select2("data")[0].text};SearchBar.prototype.getQuery=function(){return this.$search_field.val()};SearchBar.prototype.triggerSearchEvent=function(a){this.$root.trigger(this.EVENT.SEARCH_BAR_SEARCH,[a])};SearchBar.prototype.isLocationNull=function(){return""===this.$location.val()};var ShippingPreferenceCheckbox=function(a){this.$root=a;this.meet_up_radio_class=this.$meet_up_radio=this.$meet_up_area=this.delivery_radio_class=this.$delivery_radio=this.$delivery_area=null;this.init();this.initEvents()};
ShippingPreferenceCheckbox.prototype.init=function(){this.delivery_radio_class="shipping-preference-checkbox-delivery";this.meet_up_radio_class="shipping-preference-checkbox-meet-up";this.$delivery_area=this.$root.find(".shipping-preference-checkbox-delivery-area");this.$delivery_radio=this.$root.find("."+this.delivery_radio_class);this.$meet_up_area=this.$root.find(".shipping-preference-checkbox-meet-up-area");this.$meet_up_radio=this.$root.find("."+this.meet_up_radio_class)};
ShippingPreferenceCheckbox.prototype.initEvents=function(){this.$delivery_area.click(function(a){a.target&&$(a.target).hasClass(this.delivery_radio_class)||this.$delivery_radio.click()}.bind(this));this.$meet_up_area.click(function(a){a.target&&$(a.target).hasClass(this.meet_up_radio_class)||this.$meet_up_radio.click()}.bind(this))};var Site=function(a){this.$root=a;this.$open_left_side_button=this.$site_left_side_wrapper=this.$site_left_side=this.$site_left_side_remove=this.email_registration=this.$email_registration=this.$site_post_area=this.$tag_navigation=this.tag_navigation=this.search_bar=this.$search_bar=this.post_list=this.$post_list=null;this.init();this.initEvents()};Site.prototype.SCROLL_VALUE=-55;Site.prototype.CSS_CLASSES={HOME_POST_LIST:"home-post-list-container"};
Site.prototype.init=function(){this.$post_list=this.$root.find(".post-list");this.post_list=new PostList(this.$post_list);this.$search_bar=this.$root.find("#site-search-bar");this.search_bar=new SearchBar(this.$search_bar);this.$tag_navigation=this.$root.find("#tag-navigation");this.tag_navigation=new TagNavigation(this.$tag_navigation);this.$site_post_area=this.$root.find(".site-post-area");this.$email_registration=this.$root.find("#email-registration");this.email_registration=new EmailRegistration(this.$email_registration);
this.$site_left_side_wrapper=this.$root.find(".site-left-side-wrapper");this.$site_left_side=this.$root.find(".site-left-side");this.$site_left_side_remove=this.$root.find(".site-left-side-remove");this.$open_left_side_button=this.$root.find(".site-post-area-open-left-side")};
Site.prototype.initEvents=function(){this.$tag_navigation.on(TagNavigation.prototype.EVENTS.TAG_NAVIGATION_CHANGE,function(a,b){this.post_list.setNewTags(b)}.bind(this));this.$search_bar.on(SearchBar.prototype.EVENT.SEARCH_BAR_SEARCH,function(a,b){this.post_list.setQueryAndLocation(b.query,b.location)}.bind(this));$(document).scroll(function(a){100*$(document).scrollTop()/(this.post_list.getHeight()-40-$(document).height())<Site.prototype.SCROLL_VALUE&&this.post_list.getMorePosts()}.bind(this));this.$site_left_side_remove.click(function(a){this.$open_left_side_button.removeClass("site-hide");
this.$open_left_side_button.addClass("inline");this.$site_left_side.addClass("site-hide");this.$site_left_side_wrapper.addClass("site-hide");this.$site_post_area.removeClass("site-post-area-padding")}.bind(this));this.$open_left_side_button.click(function(a){this.$site_left_side.hide(100);this.$site_left_side.show(100);this.$site_left_side_wrapper.removeClass("hide-right-side");this.$site_left_side_wrapper.removeClass("site-hide");this.$site_post_area.addClass("site-post-area-padding")}.bind(this));
$(document).on("click",function(a){a.target&&0===$(a.target).closest("#tag-navigation").length&&890>window.innerWidth&&0===$(a.target).closest(".site-post-area-open-left-side").length&&(this.$site_left_side_wrapper.addClass("site-hide"),this.$site_post_area.removeClass("site-post-area-padding"))}.bind(this))};var SuggestedPost=function(a){this.$root=a;this.post_cards=[];this.init()};SuggestedPost.prototype.init=function(){$.each($(".post-card"),function(a,b){this.post_cards.push(new PostCard($(b)))}.bind(this))};var TagNavigationItem=function(a){this.$root=a;this.label=a.data("label");this.id=a.data("id");this.tick=a.data("tick");this.unfavorite_event_=this.favorite_event_=this.untick_event_=this.tick_event_=this.tick_class=this.favorite_class=this.not_favorite_class=null;this.init();this.initEvent();this.initWidgetEvents()};
TagNavigationItem.prototype.EVENTS={TAG_NAVIGATION_ITEM_TICK:"tag-navigation-item-tick",TAG_NAVIGATION_ITEM_UNTICK:"tag-navigation-item-untick",TAG_NAVIGATION_ITEM_FAVORITE:"tag-navigation-item-favorite",TAG_NAVIGATION_ITEM_UNFAVORITE:"tag-navigation-item-unfavorite"};TagNavigationItem.prototype.init=function(){this.not_favorite_class="tag-navigation-item-unfavorite";this.favorite_class="tag-navigation-item-favorite";this.tick_class="tag-navigation-item-tick"};
TagNavigationItem.prototype.initEvent=function(){$(document).on("click","#"+this.id,function(a){a.target&&0===$(a.target).closest("."+this.not_favorite_class).length&&0===$(a.target).closest("."+this.favorite_class).length&&this.toggleTick();if(a.target&&0!==$(a.target).closest("."+this.not_favorite_class).length){if(CommonLibrary.isGuest())return!1;this.triggerFavoriteEvent(this.label)}if(a.target&&0!==$(a.target).closest("."+this.favorite_class).length){if(CommonLibrary.isGuest())return!1;this.triggerUnfavoriteEvent(this.label)}a.stopPropagation()}.bind(this))};
TagNavigationItem.prototype.initWidgetEvents=function(){this.tick_event_=new CustomEvent(this.EVENTS.TAG_NAVIGATION_ITEM_TICK);this.untick_event_=new CustomEvent(this.EVENTS.TAG_NAVIGATION_ITEM_UNTICK);this.favorite_event_=new CustomEvent(this.EVENTS.TAG_NAVIGATION_ITEM_FAVORITE);this.unfavorite_event_=new CustomEvent(this.EVENTS.TAG_NAVIGATION_ITEM_UNFAVORITE)};
TagNavigationItem.prototype.toggleTick=function(){$("#"+this.id).find("."+this.tick_class).hasClass("hide")?this.triggerTickEvent(this.label):this.triggerUntickEvent(this.label)};TagNavigationItem.prototype.setUnfavorite=function(){var a=$("#"+this.id);a.find("."+this.favorite_class).addClass("hide");a.find("."+this.not_favorite_class).removeClass("hide")};TagNavigationItem.prototype.setFavorite=function(){var a=$("#"+this.id);a.find("."+this.favorite_class).removeClass("hide");a.find("."+this.not_favorite_class).addClass("hide")};
TagNavigationItem.prototype.triggerTickEvent=function(a){$("#"+this.id).trigger(this.EVENTS.TAG_NAVIGATION_ITEM_TICK,[a])};TagNavigationItem.prototype.triggerUntickEvent=function(a){$("#"+this.id).trigger(this.EVENTS.TAG_NAVIGATION_ITEM_UNTICK,[a])};TagNavigationItem.prototype.triggerFavoriteEvent=function(a){$("#"+this.id).trigger(this.EVENTS.TAG_NAVIGATION_ITEM_FAVORITE,[a])};
TagNavigationItem.prototype.triggerUnfavoriteEvent=function(a){$("#"+this.id).trigger(this.EVENTS.TAG_NAVIGATION_ITEM_UNFAVORITE,[a])};TagNavigationItem.prototype.getLabel=function(){return $("#"+this.id).data("label")};TagNavigationItem.prototype.setTick=function(a){var b=$("#"+this.id).find("."+this.tick_class);a?(b.removeClass("hide"),$("#"+this.id).data("tick",!0)):($("#"+this.id).data("tick",!1),b.addClass("hide"))};TagNavigationItem.prototype.deleteElement=function(){this.disposeItem()};
TagNavigationItem.prototype.disposeItem=function(){$(document).off("click","#"+this.id)};var TagNavigation=function(a){this.$root=a;this.id=a.data("id");this.$searched_item_area=this.$all_item_area=this.$starred_item_area=this.$searched=this.$all=this.$starred=this.$tag_navigation_search=null;this.$starred_items=[];this.$all_items=[];this.$searched_items=[];this.$all_collapse=this.$all_expand=this.$starred_collapse=this.$starred_expand=null;this.ticked_tags=[];this.init();this.initEvents();this.initWidgetEvents()};
TagNavigation.prototype.EVENTS={TAG_NAVIGATION_CHANGE:"tag-navigation-change",TAG_NAVIGATION_STARRED:"tag-navigation-starred"};
TagNavigation.prototype.init=function(){this.$starred_expand=this.$root.find(".tag-navigation-starred-expand");this.$starred_collapse=this.$root.find(".tag-navigation-starred-collapse");this.$all_expand=this.$root.find(".tag-navigation-all-expand");this.$all_collapse=this.$root.find(".tag-navigation-all-collapse");this.$tag_navigation_search=this.$root.find(".tag-navigation-search");this.$starred_item_area=this.$root.find(".tag-navigation-starred-area");this.$all_item_area=this.$root.find(".tag-navigation-all-area");
this.$searched_item_area=this.$root.find(".tag-navigation-searched-area");this.$starred=this.$root.find(".tag-navigation-starred");this.$all=this.$root.find(".tag-navigation-all");this.$searched=this.$root.find(".tag-navigation-searched");$(this.$starred_item_area.html()).filter(".tag-navigation-item").each(function(a,b){this.$starred_items.push(new TagNavigationItem($(b)))}.bind(this));$(this.$all_item_area.html()).filter(".tag-navigation-item").each(function(a,b){this.$all_items.push(new TagNavigationItem($(b)))}.bind(this))};
TagNavigation.prototype.initEvents=function(){this.$starred_collapse.click(function(a){this.$starred_item_area.addClass("site-hide");this.$starred_expand.removeClass("site-hide");this.$starred_collapse.addClass("site-hide")}.bind(this));this.$starred_expand.click(function(a){this.$starred_item_area.removeClass("site-hide");this.$starred_collapse.removeClass("site-hide");this.$starred_expand.addClass("site-hide")}.bind(this));this.$all_collapse.click(function(a){this.$all_item_area.addClass("site-hide");
this.$all_expand.removeClass("site-hide");this.$all_collapse.addClass("site-hide")}.bind(this));this.$all_expand.click(function(a){this.$all_item_area.removeClass("site-hide");this.$all_collapse.removeClass("site-hide");this.$all_expand.addClass("site-hide")}.bind(this));this.$tag_navigation_search.on("input",function(a){a=this.searchBarValue();""===a||null===a?(this.$searched.addClass("site-hide"),this.$all.removeClass("site-hide"),this.$starred.removeClass("site-hide")):(this.$searched.removeClass("site-hide"),
this.$all.addClass("site-hide"),this.$starred.addClass("site-hide"),this.searchTag(a))}.bind(this));$(document).on("click",function(a){!a.target||0!==$(a.target).closest("#"+this.id).length||890>window.innerWidth||(this.$searched.addClass("site-hide"),this.$all.removeClass("site-hide"),this.$starred.removeClass("site-hide"))}.bind(this));$(document).on(TagNavigationItem.prototype.EVENTS.TAG_NAVIGATION_ITEM_TICK,"#"+this.id,function(a,b){a.target&&$(a.target).hasClass("tag-navigation-item")&&(this.ticked_tags.push(b),
this.label_selector='.tag-navigation-item[data-label="'+b+'"]',0===this.$all_item_area.find(this.label_selector).length&&0===this.$starred_item_area.find(this.label_selector).length&&this.addTagFromSearchToAll(b,!0,"all-tags"),this.triggerChange(this.ticked_tags),this.setTick(this.$searched_items,b),console.log(this.ticked_tags),this.setTick(this.$all_items,b),this.setTick(this.$starred_items,b),a.stopPropagation())}.bind(this));$(document).on(TagNavigationItem.prototype.EVENTS.TAG_NAVIGATION_ITEM_UNTICK,
"#"+this.id,function(a,b){a.target&&$(a.target).hasClass("tag-navigation-item")&&(this.ticked_tags.remove(b),console.log(this.ticked_tags),this.triggerChange(this.ticked_tags),this.setUntick(this.$searched_items,b),this.setUntick(this.$all_items,b),this.setUntick(this.$starred_items,b))}.bind(this));$(document).on(TagNavigationItem.prototype.EVENTS.TAG_NAVIGATION_ITEM_FAVORITE,"#"+this.id,function(a,b){a.target&&$(a.target).hasClass("tag-navigation-item")&&(this.label_selector='.tag-navigation-item[data-label="'+
b+'"]',0===this.$starred_item_area.find(this.label_selector).length&&this.addTagFromSearchToStarred(b),this.sendFavoriteAjax(b),this.setFavorite(this.$searched_items,b),this.setFavorite(this.$all_items,b),this.setFavorite(this.$starred_items,b))}.bind(this));$(document).on(TagNavigationItem.prototype.EVENTS.TAG_NAVIGATION_ITEM_UNFAVORITE,"#"+this.id,function(a,b){a.target&&$(a.target).hasClass("tag-navigation-item")&&(this.label_selector='.tag-navigation-item[data-label="'+b+'"]',0!==this.$starred_item_area.find(this.label_selector).length&&
this.removeTagFromStarred(b),this.sendUnfavoriteAjax(b),this.setUnfavorite(this.$searched_items,b),this.setUnfavorite(this.$all_items,b),this.setUnfavorite(this.$starred_items,b))}.bind(this))};TagNavigation.prototype.sendFavoriteAjax=function(a){$.ajax({url:$("#base-url").val()+"/tags/request-starred",type:"post",data:{tag_name:a},success:function(a){}})};TagNavigation.prototype.sendUnfavoriteAjax=function(a){$.ajax({url:$("#base-url").val()+"/tags/cancel-starred",type:"post",data:{tag_name:a},success:function(a){}})};
TagNavigation.prototype.addTagFromSearchToStarred=function(a){$.ajax({url:$("#base-url").val()+"/tags/get-tag",data:{label:a,tick:-1!==this.ticked_tags.indexOf(a),prepend_id:"starred-tags",starred:!0},type:"post",context:this,success:function(a){a=JSON.parse(a);1===a.status&&(this.$starred_item_area.prepend(a.views),this.$starred_items.push(new TagNavigationItem($(a.views))))}})};
TagNavigation.prototype.removeTagFromStarred=function(a){for(var b=0;b<this.$starred_items.length;b++)this.$starred_items[b].getLabel()===a&&this.$starred_items[b].deleteElement();this.$starred_item_area.find('.tag-navigation-item[data-label="'+a+'"]').remove()};
TagNavigation.prototype.addTagFromSearchToAll=function(a,b,c){$.ajax({url:$("#base-url").val()+"/tags/get-tag",data:{label:a,tick:b,prepend_id:c,favorite:!1},type:"post",context:this,success:function(a){a=JSON.parse(a);1===a.status&&(this.$all_item_area.prepend(a.views),this.$all_items.push(new TagNavigationItem($(a.views))))}})};TagNavigation.prototype.setFavorite=function(a,b){for(var c=0;c<a.length;c++)a[c].getLabel()===b&&a[c].setFavorite()};
TagNavigation.prototype.setUnfavorite=function(a,b){for(var c=0;c<a.length;c++)a[c].getLabel()===b&&a[c].setUnfavorite()};TagNavigation.prototype.setTick=function(a,b){for(var c=0;c<a.length;c++)a[c].getLabel()===b&&a[c].setTick(!0)};TagNavigation.prototype.setUntick=function(a,b){for(var c=0;c<a.length;c++)a[c].getLabel()===b&&a[c].setTick(!1)};
TagNavigation.prototype.searchTag=function(a){$.ajax({url:$("#base-url").val()+"/tags/search-tag",type:"post",context:this,data:{query:a,ticked_tags:this.ticked_tags},success:function(a){a=JSON.parse(a);if(1===a.status){this.$searched_item_area.html(a.views);for(a=0;a<this.$searched_items.length;a++)this.$searched_items[a].deleteElement();this.$searched_items=[];$(this.$searched_item_area.html()).filter(".tag-navigation-item").each(function(a,b){this.$searched_items.push(new TagNavigationItem($(b)))}.bind(this))}}})};
TagNavigation.prototype.searchBarValue=function(){return this.$tag_navigation_search.val()};TagNavigation.prototype.initWidgetEvents=function(){this.tag_navigation_change_=new CustomEvent(this.EVENTS.TAG_NAVIGATION_CHANGE);this.tag_navigation_starred_=new CustomEvent(this.EVENTS.TAG_NAVIGATION_STARRED)};TagNavigation.prototype.triggerChange=function(a){this.$root.trigger(this.EVENTS.TAG_NAVIGATION_CHANGE,[a])};
